update yaml

diff --git a/.github/workflows/roadmap.yml b/.github/workflows/roadmap.yml
--- a/.github/workflows/roadmap.yml
+++ b/.github/workflows/roadmap.yml
@@ -28,6 +28,7 @@ jobs:
       - name: Check Marker File Existence
         id: marker
         run: |
+          python toto.py
           if [ -f "$LOCK_FILE" ]; then
             echo "Plan marker found, skipping workflow."
             echo "exists=true" >> $GITHUB_OUTPUT
@@ -35,27 +36,27 @@ jobs:
             echo "exists=false" >> $GITHUB_OUTPUT
           fi
 
-      # - name: Setup UV
-      #   if: steps.marker.outputs.already_deployed == 'false'
-      #   uses: astral-sh/setup-uv@v3
+      # # - name: Setup UV
+      # #   if: steps.marker.outputs.already_deployed == 'false'
+      # #   uses: astral-sh/setup-uv@v3
 
-      - name: Validate Project Plan
-        id: validate
-        # if: steps.marker.outputs.already_deployed == 'false'
-      #   run: |
-      #     uv run \
-      #         --no-project \
-      #         --python 3.14 \
-      #         --with "pydantic>=2.12,<2.13" \
-      #         "$PLAN_CHECKER" --plan "$PLAN"
-        run: exit 1
-        continue-on-error: ${{ github.event.inputs.force_apply == 'false'}}
+      # - name: Validate Project Plan
+      #   id: validate
+      #   # if: steps.marker.outputs.already_deployed == 'false'
+      # #   run: |
+      # #     uv run \
+      # #         --no-project \
+      # #         --python 3.14 \
+      # #         --with "pydantic>=2.12,<2.13" \
+      # #         "$PLAN_CHECKER" --plan "$PLAN"
+      #   run: exit 1
+      #   continue-on-error: ${{ github.event.inputs.force_apply == 'false'}}
 
-      - name: Deploy GitHub Issues
-      #   if: |
-      #     steps.validate.outcome == 'success' ||
-      #     (steps.validate.outcome == 'failure' && github.event.inputs.force_deploy == 'true')
-      #   env:
-      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        # run: uv run "$PLAN_DEPLOYER" --plan "$PLAN" --marker "$LOCK_FILE"
-        run: echo "Deploying plan..."
+      # - name: Deploy GitHub Issues
+      # #   if: |
+      # #     steps.validate.outcome == 'success' ||
+      # #     (steps.validate.outcome == 'failure' && github.event.inputs.force_deploy == 'true')
+      # #   env:
+      # #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   # run: uv run "$PLAN_DEPLOYER" --plan "$PLAN" --marker "$LOCK_FILE"
+      #   run: echo "Deploying plan..."
